In [1]:
import numpy as np

In [2]:
x = np.zeros(10)

In [3]:
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
y = np.arange(10,49)

In [5]:
y

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

In [6]:
y.shape

(39,)

In [7]:
y.dtype

dtype('int32')

In [8]:
print(np.__version__)
print(np.show_config())

1.18.1
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/zaheer.ahmed/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/zaheer.ahmed/Anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/zaheer.ahmed/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019

In [9]:
y.ndim

1

In [10]:
np.full((2, 2), True)

array([[ True,  True],
       [ True,  True]])

In [11]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [12]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [13]:
z = y[::-1]

In [14]:
z

array([48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10])

In [15]:
(np.arange(10) == 4).astype(int)

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

In [16]:
#Identity array

In [17]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
#change data type of array

In [19]:
arr = np.array([1, 2, 3, 4, 5])

In [20]:
arr = arr.astype(np.float32)

In [21]:
arr.dtype

dtype('float32')

In [22]:
#Multiply array

In [23]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]])  

arr2 = np.array([[0., 4., 1.],

           [7., 2., 12.]])

In [24]:
arr1*arr2

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

In [25]:
#comparing array

In [26]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]]) 

arr2 = np.array([[0., 4., 1.],

            [7., 2., 12.]])

In [27]:
arr3 = arr1 == arr2

In [28]:
arr3

array([[False, False, False],
       [False, False, False]])

In [29]:
#odd number form array

In [30]:
a = np.array([0,1,2,3,4,5,6,6,7,7,8,9])

In [31]:
a[a % 2 == 1]

array([1, 3, 5, 7, 7, 9])

In [32]:
#replace odd number with -1
a[a % 2 == 1] = -1

In [33]:
a

array([ 0, -1,  2, -1,  4, -1,  6,  6, -1, -1,  8, -1])

In [34]:
# Replace the values of indexes 5,6,7 and 8 to 12
arr = np.arange(10)

In [35]:
a[5:9] = 12

In [36]:
a

array([ 0, -1,  2, -1,  4, 12, 12, 12, 12, -1,  8, -1])

In [37]:
#Create a 2d array with 1 on the border and 0 inside

In [38]:
x = np.ones((5,5))

In [39]:
x[1:-1,1:-1] = 0

In [40]:
x

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [41]:
#Level Medium

In [42]:
#Replace the value 5 to 12

In [43]:
arr2d = np.array([[1, 2, 3],

            [4, 5, 6], 

            [7, 8, 9]])

In [44]:
arr2d[1][1] = 12

In [45]:
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

In [46]:
#Convert all the values of 1st array to 64

In [47]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [48]:
arr3d[0][0] = 64

In [49]:
arr3d

array([[[64, 64, 64],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [50]:
print("abc")

abc


In [51]:
arraay2dim = np.array([[0,1,2],[3,4,5],[6,7,8]])

In [52]:
arraay2dim

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [53]:
arraay2dim[0]

array([0, 1, 2])

In [54]:
arraay2dim[1]

array([3, 4, 5])

In [55]:
arraay2dim[2]

array([6, 7, 8])

In [56]:
arr_random = np.random.rand(10,10)

In [57]:
arr_random

array([[0.93639743, 0.93658868, 0.23196219, 0.02813058, 0.65476488,
        0.27355605, 0.84062781, 0.11783531, 0.05573988, 0.32022819],
       [0.94985477, 0.01811947, 0.84009397, 0.64864688, 0.06924431,
        0.57134614, 0.78203667, 0.30789453, 0.89160922, 0.99316638],
       [0.76437994, 0.62881967, 0.48737737, 0.42474473, 0.92534313,
        0.56347823, 0.49162552, 0.70568701, 0.14068316, 0.38792517],
       [0.36025733, 0.97879492, 0.70178499, 0.3289755 , 0.59877331,
        0.79250022, 0.72459082, 0.51438441, 0.12870563, 0.59058202],
       [0.66054357, 0.53099809, 0.73393387, 0.39830615, 0.43062895,
        0.59916642, 0.51954853, 0.30981273, 0.59716834, 0.94222839],
       [0.02331076, 0.80560585, 0.28941169, 0.91163959, 0.00309017,
        0.83952489, 0.44375759, 0.2282391 , 0.61541178, 0.91872868],
       [0.53235584, 0.14657268, 0.83727516, 0.71526266, 0.87038725,
        0.63534694, 0.63176678, 0.62056324, 0.60474158, 0.35541769],
       [0.60050513, 0.94938275, 0.1225483

In [58]:
np.max(arr_random)

0.9931663784129008

In [59]:
np.min(arr_random)

0.0030901661209168374

In [60]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [61]:
np.intersect1d(a,b)

array([2, 4])

In [62]:
np.in1d(a,b)

array([False,  True, False,  True, False,  True, False,  True, False,
       False])

In [63]:
np.intersect1d(a, b, return_indices=True)

(array([2, 4]), array([1, 5], dtype=int64), array([1, 5], dtype=int64))

In [64]:
np.where(a == b)

(array([1, 3, 5, 7], dtype=int64),)

In [65]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)

In [66]:
data

array([[ 0.94208674, -1.08006723, -0.90313083, -0.36909103],
       [-1.79641032,  1.33638371,  0.60584361,  1.37783807],
       [ 0.67778413, -2.07556796, -0.76044334, -1.72096647],
       [-0.4754724 , -1.72716666, -1.21800518, -0.18360721],
       [ 0.79263499, -0.59003445,  0.06690903,  0.09329572],
       [-0.02408961,  0.36443943,  0.88250717, -0.8093133 ],
       [-0.30805555,  0.23507564,  0.03405291,  0.70788071]])

In [67]:
np.where(names[names != "Will"])

(array([0, 1, 2, 3, 4], dtype=int64),)

In [68]:
data[np.where(names[names != "Will"])[0]]

array([[ 0.94208674, -1.08006723, -0.90313083, -0.36909103],
       [-1.79641032,  1.33638371,  0.60584361,  1.37783807],
       [ 0.67778413, -2.07556796, -0.76044334, -1.72096647],
       [-0.4754724 , -1.72716666, -1.21800518, -0.18360721],
       [ 0.79263499, -0.59003445,  0.06690903,  0.09329572]])

In [69]:
data[np.where(names[(names != "Will") & (names != "Joe")])[0]]

array([[ 0.94208674, -1.08006723, -0.90313083, -0.36909103],
       [-1.79641032,  1.33638371,  0.60584361,  1.37783807]])

In [70]:
#Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [71]:
twod_array = np.arange(1,16,dtype=float).reshape(5,3)

In [72]:
twod_array

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.],
       [13., 14., 15.]])

In [73]:
#Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [74]:
threed_array = np.arange(1,17,dtype=float).reshape(2,2,4)

In [75]:
threed_array

array([[[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.]],

       [[ 9., 10., 11., 12.],
        [13., 14., 15., 16.]]])

In [76]:
#Swap axes of the array you created in Question 32

In [77]:
np.swapaxes(threed_array,0,2)

array([[[ 1.,  9.],
        [ 5., 13.]],

       [[ 2., 10.],
        [ 6., 14.]],

       [[ 3., 11.],
        [ 7., 15.]],

       [[ 4., 12.],
        [ 8., 16.]]])

In [78]:
arr_seq = np.sqrt(np.arange(10))

In [79]:
arr_seq[arr_seq < 2] = 1

In [80]:
arr_seq

array([1.        , 1.        , 1.        , 1.        , 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [81]:
#Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [82]:
arr1_random = np.random.uniform(low=1, high=50, size=(12,))

In [83]:
arr1_random

array([27.74529509, 39.36459326, 12.07046428, 35.15448704, 12.78348684,
       18.00250853,  7.37461729, 31.45441084, 49.01415444, 10.63225906,
       28.65237043, 30.72923633])

In [84]:
arr2_random = np.random.uniform(low=1, high=50, size=(12,))

In [85]:
arr2_random

array([34.04640301, 48.00703244, 47.27683715, 41.44915822,  6.06249652,
       39.07119498, 21.84989012, 35.4097441 ,  6.23229668,  7.70107294,
       31.82646931,  1.78819586])

In [86]:
arr3_random_max = np.maximum(arr1_random,arr2_random)

In [87]:
arr3_random_max

array([34.04640301, 48.00703244, 47.27683715, 41.44915822, 12.78348684,
       39.07119498, 21.84989012, 35.4097441 , 49.01415444, 10.63225906,
       31.82646931, 30.72923633])

In [88]:
#names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
# find the unique and sort out

In [89]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [90]:
np.sort(np.unique(names))

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [91]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [92]:
#a = np.array([1,2,3,4,5]) b = np.array([5,6,7,8,9])
#From array a remove all items present in array b

In [93]:
a = np.array([1,2,3,4,5]) 
b = np.array([5,6,7,8,9])
np.setdiff1d(a, b, assume_unique=False)

array([1, 2, 3, 4])

In [94]:
#Following is the input NumPy array delete column two and insert following new column in its place.

In [96]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])

In [106]:
newColumn = np.array([[10,10,10]])

In [107]:
sampleArray[:,2] = newColumn

In [108]:
sampleArray

array([[34, 43, 10],
       [82, 22, 10],
       [53, 94, 10]])

In [109]:
# dot product

In [112]:
x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
y = np.array([[6., 23.], [-1, 7], [8, 9]])

In [113]:
np.dot(x,y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [114]:
#Generate a matrix of 20 random values and find its cumulative sum

In [115]:
randomarr = np.random.rand(20)

In [116]:
randomarr

array([0.35189059, 0.94327959, 0.58595054, 0.13183989, 0.82057621,
       0.92563452, 0.4122814 , 0.81936899, 0.79921707, 0.11352802,
       0.03514944, 0.06697796, 0.14334946, 0.27719856, 0.70758556,
       0.29108894, 0.21578644, 0.37103597, 0.84199431, 0.46250782])

In [117]:
randomarr.sum()

9.31624128544711